language: swift
osx_image: xcode11.3
xcode_workspace: ImageGalleryApp.xcworkspace
xcode_scheme: ImageGalleryApp
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 8
before_install:
  - pod install
after_success:
  - bash <(curl -s https://codecov.io/bash) -X xcodellvm
