language: swift
osx_image: xcode11.3
xcode_workspace: ImageGalleryApp.xcworkspace
xcode_scheme: ImageGalleryApp
xcode_destination: platform=iOS Simulator,OS=13.3,name=iPhone 8
before_install:
  - pod install --repo-update
after_success:
  - bash <(curl -s https://codecov.io/bash) -t c50c028f-9fcf-45d9-8dc4-931410f1da6e
